baseURL = "https://shaolang.github.io/"
languageCode = "en-us"
title = "Bit by bit"

[params]
description = "Biz analyst by day, coder by night, ML practitioner in the making"
copyright = "Creative Commons Attribution-ShareAlike 4.0 International"
